### ISSUE TITLE
unable to open pickle of skipthoughts

### ISSUE THREAD

**Issue by Exception4U** [paarthneekhara/text-to-image#10]
XXX@XXX:~/codes/python_codes/text-to-image$ python generate_thought_vectors.py --caption_file="Data/sample_captions.txt"
['the flower shown has yellow anther red pistil and bright red petals']
Loading model parameters...
Compiling encoders...
Loading tables...
Traceback (most recent call last):
  File "generate_thought_vectors.py", line 33, in <module>
    main()
  File "generate_thought_vectors.py", line 23, in main
    model = skipthoughts.load_model()
  File "/home/tushar/codes/python_codes/text-to-image/skipthoughts.py", line 60, in load_model
    utable, btable = load_tables()
  File "/home/tushar/codes/python_codes/text-to-image/skipthoughts.py", line 80, in load_tables
    utable = numpy.load(path_to_tables + 'utable.npy')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 406, in load
    pickle_kwargs=pickle_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/format.py", line 637, in read_array
    array = pickle.load(fp, **pickle_kwargs)
EOFError

**Comment by paarthneekhara** [comment]
I guess you did not download data files required for skip-thought vectors. Follow the datasets instructions in the readme.
