### ISSUE TITLE
data loader running error

### ISSUE THREAD

**Issue by komala1234** [paarthneekhara/text-to-image#25]
while running the (data_loader.py) i am getting the following errors. if any one know the solutions please let me know

Traceback (most recent call last):
  File "/home/komali/PycharmProjects/text-to-image-master/data_loader.py", line 113, in <module>
    main()
  File "/home/komali/PycharmProjects/text-to-image-master/data_loader.py", line 108, in main
    save_caption_vectors_flowers(args.data_dir)
  File "/home/komali/PycharmProjects/text-to-image-master/data_loader.py", line 85, in save_caption_vectors_flowers
    encoded_captions[img] = skipthoughts.encode(model, image_captions[img])
  File "/home/komali/PycharmProjects/text-to-image-master/skipthoughts.py", line 96, in encode
    X = preprocess(X)
  File "/home/komali/PycharmProjects/text-to-image-master/skipthoughts.py", line 160, in preprocess
    sent_detector = nltk.data.load('tokenizers/punkt/english.pickle')
  File "/home/komali/anaconda2/lib/python2.7/site-packages/nltk/data.py", line 801, in load
    opened_resource = _open(resource_url)
  File "/home/komali/anaconda2/lib/python2.7/site-packages/nltk/data.py", line 919, in _open
    return find(path_, path + ['']).open()
  File "/home/komali/anaconda2/lib/python2.7/site-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource u'tokenizers/punkt/english.pickle' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/home/komali/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''

**Comment by YuanEZhou** [comment]
import nltk
nltk.download('punkt')
