### ISSUE TITLE
training error 

### ISSUE THREAD

**Issue by dheeru999** [paarthneekhara/text-to-image#26]
while running the (train.py) i got the below errors. if any one knew tha solution please let me know

Traceback (most recent call last):
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/train.py", line 250, in <module>
    main()
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/train.py", line 77, in main
    input_tensors, variables, loss, outputs, checks = gan.build_model()
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/model.py", line 39, in build_model
    disc_real_image, disc_real_image_logits   = self.discriminator(t_real_image, t_real_caption)
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/model.py", line 159, in discriminator
    h0 = ops.lrelu(ops.conv2d(image, self.options['df_dim'], name = 'd_h0_conv')) #32
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/Utils/ops.py", line 76, in conv2d
    initializer=tf.truncated_normal_initializer(stddev=stddev))
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 682, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable d_h0_conv/w does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

Process finished with exit code 1

**Comment by divyat09** [comment]
I am also facing a similar problem:

  File "train.py", line 256, in <module>
    main()
  File "train.py", line 76, in main
    input_tensors, variables, loss, outputs, checks = gan.build_model()
  File "/home/divyat/Desktop/Workspace/UGP/Visual_Program_Synthesis/text-to-image-master-editable/model.py", line 40, in build_model
    disc_wrong_image, disc_wrong_image_logits   = self.discriminator(t_wrong_image, t_real_caption, reuse = True)
  File "/home/divyat/Desktop/Workspace/UGP/Visual_Program_Synthesis/text-to-image-master-editable/model.py", line 167, in discriminator
    h1 = ops.lrelu( self.d_bn1(ops.conv2d(h0, self.options['df_dim']*2, name = 'd_h1_conv'))) #16
  File "/home/divyat/Desktop/Workspace/UGP/Visual_Program_Synthesis/text-to-image-master-editable/Utils/ops.py", line 34, in __call__
    ema_apply_op = self.ema.apply([batch_mean, batch_var])
  File "/home/divyat/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 375, in apply
    colocate_with_primary=(var.op.type in ["Variable", "VariableV2"]))
  File "/home/divyat/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/divyat/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 149, in create_slot_with_initializer
    dtype)
  File "/home/divyat/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "/home/divyat/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/divyat/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/divyat/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/divyat/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/divyat/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 682, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable d_bn1/d_bn1_2/moments/Squeeze/ExponentialMovingAverage/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by divyat09** [comment]
I got this error resolved by running on tensorflow version 0.11
