### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by dheeru999** [paarthneekhara/text-to-image#27]
While running the (Train. py) i am facing the following errors. Please help me to solve those errors.

/usr/bin/python2.7 /home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/train.py
Traceback (most recent call last):
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/train.py", line 250, in <module>
    main()
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/train.py", line 77, in main
    input_tensors, variables, loss, outputs, checks = gan.build_model()
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/model.py", line 37, in build_model
    fake_image = self.generator(t_z, t_real_caption)
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/model.py", line 137, in generator
    z_concat = tf.concat(1, [t_z, reduced_text_embedding])
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1061, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/mcis-lap-40/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

Process finished with exit code 1

**Comment by paarthneekhara** [comment]
This is again a tensorflow version issue.. Please check the function definition in your tf version and modify the method call accordingly - tf.concat
=> tf.concat([t_z, reduced_text_embedding], axis=1)
You may need to update some other method calls as well.

**Comment by dheeru999** [comment]
Thanks for responding.............

=> tf.concat([t_z, reduced_text_embedding], axis=1)- I have changed this ,but still the error remains same...

(You may need to update some other method calls as well)-- Can u mention what are the other method calls that i need to update......
