### ISSUE TITLE
train errors

### ISSUE THREAD

**Issue by anushaGundapaneni** [paarthneekhara/text-to-image#28]
when i tried to run train.py i am getting the below error. please help me to slove it.if any one knew the answer please let me know

Traceback (most recent call last):
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/train.py", line 256, in <module>
    main()
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-master/train.py", line 106, in main
    loaded_data)
TypeError: 'NoneType' object is not iterable

**Comment by dheeru999** [comment]
Use (TensorFlow) version 0.11.0 -- u can resolve the errors.
