### ISSUE TITLE
Training MS_COCO Error

### ISSUE THREAD

**Issue by dheeru999** [paarthneekhara/text-to-image#29]
When i'am trying to Run (Train .py) By using MS-COCO dataset . I'am facing the below errors.

please provide suggestions to solve those errors.

**ERRORS:**
Traceback (most recent call last):
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-generation/train.py", line 227, in <module>
    main()
  File "/home/mcis-lap-40/raviwork/Tensorflow_Models/text-to-image-generation/train.py", line 105, in main
    loaded_data)
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1

**Comment by LBJYPY** [comment]
have you solved this problem？
