### ISSUE TITLE
Error: d_bn1/d_bn1_2/moments/Squeeze/ExponentialMovingAverage/ does not exist

### ISSUE THREAD

**Issue by 314rated** [paarthneekhara/text-to-image#42]
On running generate_images script, following are errors received.
Could be please suggest a fix for this?
Thanks

====================================================
python generate_images.py --model_path=Data/Models/latest_model_flowers_temp.ckpt --n_images=8

Traceback (most recent call last):
  File "generate_images.py", line 106, in <module>
    main()
  File "generate_images.py", line 64, in main
    _, _, _, _, _ = gan.build_model()
  File "repo/model.py", line 40, in build_model
    disc_wrong_image, disc_wrong_image_logits   = self.discriminator(t_wrong_image, t_real_caption, reuse = True)
  File "repo/model.py", line 161, in discriminator
    h1 = ops.lrelu( self.d_bn1(ops.conv2d(h0, self.options['df_dim']*2, name = 'd_h1_conv'))) #16
  File "repo/Utils/ops.py", line 34, in __call__
    ema_apply_op = self.ema.apply([batch_mean, batch_var])
  File "path/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 403, in apply
    colocate_with_primary=(var.op.type in ["Variable", "VariableV2"]))
  File "path/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "path/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 151, in create_slot_with_initializer
    dtype)
  File "path/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 67, in _create_slot_var
    validate_shape=validate_shape)
  File "path/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1297, in get_variable
    constraint=constraint)
  File "path/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1093, in get_variable
    constraint=constraint)
  File "path/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 439, in get_variable
    constraint=constraint)
  File "path/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 408, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "path/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 765, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
**ValueError: Variable d_bn1/d_bn1_2/moments/Squeeze/ExponentialMovingAverage/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?**

**Comment by namrathadeepthi** [comment]
I am struggling with the same error, is there any fix?

**Comment by ravindra82** [comment]
Try adding the below line before ema.apply in ops.py
with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE):

This resolved this error for me.

**Comment by Wentong-DST** [comment]
I'm using TensorFlow v0.12. This works for me:
add ``with tf.variable_scope(tf.get_variable_scope(), reuse=False):``
before ``ema.apply``

**Comment by gentlebreeze1** [comment]
where should with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE): add?
before ema_apply_op = self.ema.apply([batch_mean, batch_var])?
but it does not work. @ravindra82

**Comment by gentlebreeze1** [comment]
i use with tf.variable_scope(tf.get_variable_scope(), reuse=False): replace with tf.variable_scope(self.name,reuse=tf.AUTO_REUSE) as scope: in ops.py.
but i get ValueError: Trying to share variable beta, but specified shape (256,) and found shape (512,).
what is wrong?

**Comment by gentlebreeze1** [comment]
i use with tf.variable_scope(tf.get_variable_scope(), reuse=False): replace with tf.variable_scope(self.name,reuse=tf.AUTO_REUSE) as scope: in ops.py.
but i get ValueError: Trying to share variable beta, but specified shape (256,) and found shape (512,).
what is wrong? @ravindra82

**Comment by anastasiagkou** [comment]
@gentlebreeze1 did you find solution ? because i have the same problem.

**Comment by remyavijeesh22** [comment]
i use with tf.variable_scope(self.name,reuse=tf.AUTO_REUSE) as scope: in ops.py. but an occured like this 

WARNING:tensorflow:From /home/hp/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "train.py", line 238, in <module>
    main()
  File "train.py", line 76, in main
    input_tensors, variables, loss, outputs, checks = gan.build_model()
  File "/home/hp/Gan_project_main/text_image_gan/model.py", line 43, in build_model
    g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(disc_fake_image_logits, tf.ones_like(disc_fake_image)))
  File "/home/hp/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_impl.py", line 157, in sigmoid_cross_entropy_with_logits
    labels, logits)
  File "/home/hp/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2315, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sigmoid_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
how can i solve this pls reply as soon as possible

**Comment by siddas27** [comment]
@remyavijeesh22
Use `g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits = disc_fake_image_logits, labels = tf.ones_like(disc_fake_image)))`
instead of  `g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(disc_fake_image_logits, tf.ones_like(disc_fake_image)))`

**Comment by kckenneth** [comment]
> @remyavijeesh22
> Use `g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits = disc_fake_image_logits, labels = tf.ones_like(disc_fake_image)))`
> instead of `g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(disc_fake_image_logits, tf.ones_like(disc_fake_image)))`

I changed that. The error then goes on to show that 
`d_loss1` bla bla bla, so I added `logits=` and `labels=` the same style in `g_loss`.  I made changes for `d_loss2` and `d_loss3` as well. 

When I run `$ python2 generate_images.py --model_path=Data/Models/latest_model_flowers_temp.ckpt --n_images=8`

Another error 
```
Tensor name "d_bn1_1/moments/Squeeze/ExponentialMovingAverage" not found in checkpoint files Data/Models/latest_model_flowers_temp.ckpt
	 [[node save/RestoreV2 (defined at generate_images.py:66) ]]
```
Any suggestion?

**Comment by urushi3** [comment]
I tried all of the above.
After that, the following error occurred.
Could be please suggest a fix for this?
===================================================================
WARNING: Logging before flag parsing goes to stderr.
W0701 14:25:53.762808 12404 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:12: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0701 14:25:53.773448 12404 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\model.py:32: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0701 14:25:53.775442 12404 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:113: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

W0701 14:25:53.803344 12404 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:33: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.

W0701 14:25:53.804338 12404 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:33: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

W0701 14:25:54.242295 12404 deprecation.py:323] From C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0701 14:25:54.263106 12404 deprecation_wrapper.py:119] From train.py:78: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

Traceback (most recent call last):
  File "train.py", line 238, in <module>
    main()
  File "train.py", line 78, in main
    d_optim = tf.train.AdamOptimizer(args.learning_rate, beta1 = args.beta1).minimize(loss['d_loss'], var_list=variables['d_vars'])
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 413, in minimize
    name=name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\adam.py", line 131, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 1155, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 190, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 164, in create_slot_with_initializer
    dtype)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 74, in _create_slot_var
    validate_shape=validate_shape)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1496, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1239, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 562, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 514, in _true_getter
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 882, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

**Comment by urushi3** [comment]
I tried all of the above.
Then you will see the following error.
Could be please suggest a fix for this?
===================================================================
WARNING: Logging before flag parsing goes to stderr.
W0701 14:48:43.140326 17436 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:12: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0701 14:48:43.161990 17436 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\model.py:32: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0701 14:48:43.170435 17436 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:113: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

W0701 14:48:43.201077 17436 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:33: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.

W0701 14:48:43.202105 17436 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:33: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

W0701 14:48:43.631316 17436 deprecation.py:323] From C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0701 14:48:43.651262 17436 deprecation_wrapper.py:119] From train.py:78: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

Traceback (most recent call last):
  File "train.py", line 238, in <module>
    main()
  File "train.py", line 78, in main
    d_optim = tf.train.AdamOptimizer(args.learning_rate, beta1 = args.beta1).minimize(loss['d_loss'], var_list=variables['d_vars'])
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 413, in minimize
    name=name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\adam.py", line 131, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 1155, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 190, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 164, in create_slot_with_initializer
    dtype)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 74, in _create_slot_var
    validate_shape=validate_shape)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1496, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1239, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 562, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 514, in _true_getter
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 882, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

**Comment by urushi3** [comment]
I tried all of the above.
Then you will see the following error.
Could be please suggest a fix for this?
WARNING: Logging before flag parsing goes to stderr.
W0701 14:48:43.140326 17436 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:12: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0701 14:48:43.161990 17436 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\model.py:32: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0701 14:48:43.170435 17436 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:113: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

W0701 14:48:43.201077 17436 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:33: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.

W0701 14:48:43.202105 17436 deprecation_wrapper.py:119] From C:\Users\c0116\Anaconda3\envs\py36\text-to-image-master\Python 3 Codes\Utils\ops.py:33: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

W0701 14:48:43.631316 17436 deprecation.py:323] From C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0701 14:48:43.651262 17436 deprecation_wrapper.py:119] From train.py:78: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

Traceback (most recent call last):
  File "train.py", line 238, in <module>
    main()
  File "train.py", line 78, in main
    d_optim = tf.train.AdamOptimizer(args.learning_rate, beta1 = args.beta1).minimize(loss['d_loss'], var_list=variables['d_vars'])
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 413, in minimize
    name=name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\adam.py", line 131, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 1155, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 190, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 164, in create_slot_with_initializer
    dtype)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 74, in _create_slot_var
    validate_shape=validate_shape)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1496, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1239, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 562, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 514, in _true_getter
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 882, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

**Comment by urushi3** [comment]
I tried all of the above.
Then you will see the following error.
Could be please suggest a fix for this?
===================================================================
Traceback (most recent call last):
  File "train.py", line 238, in <module>
    main()
  File "train.py", line 78, in main
    d_optim = tf.train.AdamOptimizer(args.learning_rate, beta1 = args.beta1).minimize(loss['d_loss'], var_list=variables['d_vars'])
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 413, in minimize
    name=name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\adam.py", line 131, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 1155, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 190, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 164, in create_slot_with_initializer
    dtype)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 74, in _create_slot_var
    validate_shape=validate_shape)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1496, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1239, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 562, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 514, in _true_getter
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 882, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

**Comment by urushi3** [comment]
I tried all of the above.
Then you will see the following error.
Could be please suggest a fix for this?

===================================================================Traceback (most recent call last):
  File "train.py", line 238, in <module>
    main()
  File "train.py", line 78, in main
    d_optim = tf.train.AdamOptimizer(args.learning_rate, beta1 = args.beta1).minimize(loss['d_loss'], var_list=variables['d_vars'])
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 413, in minimize
    name=name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 597, in apply_gradients
    self._create_slots(var_list)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\adam.py", line 131, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 1155, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 190, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 164, in create_slot_with_initializer
    dtype)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 74, in _create_slot_var
    validate_shape=validate_shape)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1496, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1239, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 562, in get_variable
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 514, in _true_getter
    aggregation=aggregation)
  File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 882, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

**Comment by silverlilin** [comment]
> @remyavijeesh22
> Use `g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits = disc_fake_image_logits, labels = tf.ones_like(disc_fake_image)))`
> instead of `g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(disc_fake_image_logits, tf.ones_like(disc_fake_image)))`

why I did this, but it was useless. I still reported the same mistake.

**Comment by silverlilin** [comment]
> I tried all of the above.
> Then you will see the following error.
> Could be please suggest a fix for this?
> 
> ===================================================================Traceback (most recent call last):
> File "train.py", line 238, in
> main()
> File "train.py", line 78, in main
> d_optim = tf.train.AdamOptimizer(args.learning_rate, beta1 = args.beta1).minimize(loss['d_loss'], var_list=variables['d_vars'])
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 413, in minimize
> name=name)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 597, in apply_gradients
> self._create_slots(var_list)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\adam.py", line 131, in _create_slots
> self._zeros_slot(v, "m", self._name)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\optimizer.py", line 1155, in _zeros_slot
> new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 190, in create_zeros_slot
> colocate_with_primary=colocate_with_primary)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 164, in create_slot_with_initializer
> dtype)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\training\slot_creator.py", line 74, in _create_slot_var
> validate_shape=validate_shape)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1496, in get_variable
> aggregation=aggregation)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1239, in get_variable
> aggregation=aggregation)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 562, in get_variable
> aggregation=aggregation)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 514, in _true_getter
> aggregation=aggregation)
> File "C:\Users\c0116\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 882, in _get_single_variable
> "reuse=tf.AUTO_REUSE in VarScope?" % name)
> ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

did you solve this problem? i also meet the same error that i have no way to solve it, can you give me some suggestion?

**Comment by 18398639574** [comment]
> > @remyavijeesh22
> > Use `g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits = disc_fake_image_logits, labels = tf.ones_like(disc_fake_image)))`
> > instead of `g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(disc_fake_image_logits, tf.ones_like(disc_fake_image)))`
> 
> I changed that. The error then goes on to show that
> `d_loss1` bla bla bla, so I added `logits=` and `labels=` the same style in `g_loss`. I made changes for `d_loss2` and `d_loss3` as well.
> 
> When I run `$ python2 generate_images.py --model_path=Data/Models/latest_model_flowers_temp.ckpt --n_images=8`
> 
> Another error
> 
> ```
> Tensor name "d_bn1_1/moments/Squeeze/ExponentialMovingAverage" not found in checkpoint files Data/Models/latest_model_flowers_temp.ckpt
> 	 [[node save/RestoreV2 (defined at generate_images.py:66) ]]
> ```
> 
> Any suggestion?

hello,have you solved this problem?

**Comment by RohanBolusani** [comment]
> > > @remyavijeesh22
> > > Use `g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits = disc_fake_image_logits, labels = tf.ones_like(disc_fake_image)))`
> > > instead of `g_loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(disc_fake_image_logits, tf.ones_like(disc_fake_image)))`
> > 
> > 
> > I changed that. The error then goes on to show that
> > `d_loss1` bla bla bla, so I added `logits=` and `labels=` the same style in `g_loss`. I made changes for `d_loss2` and `d_loss3` as well.
> > When I run `$ python2 generate_images.py --model_path=Data/Models/latest_model_flowers_temp.ckpt --n_images=8`
> > Another error
> > ```
> > Tensor name "d_bn1_1/moments/Squeeze/ExponentialMovingAverage" not found in checkpoint files Data/Models/latest_model_flowers_temp.ckpt
> > 	 [[node save/RestoreV2 (defined at generate_images.py:66) ]]
> > ```
> > 
> > 
> > Any suggestion?
> 
> hello,have you solved this problem?

hey were you able to fix this?

**Comment by liumarcus70s** [comment]
same problem T_T
