### ISSUE TITLE
data_loader error  (need help) 

### ISSUE THREAD

**Issue by LBJYPY** [paarthneekhara/text-to-image#47]
/home/amax/anaconda3/bin/python /home/amax/ypy/text-to-image-master/Codes3/data_loader.py
['image_00301.jpg', 'image_00302.jpg', 'image_00303.jpg', 'image_00304.jpg', 'image_00305.jpg', 'image_00306.jpg', 'image_00307.jpg', 'image_00308.jpg', 'image_00309.jpg', 'image_00310.jpg', 'image_00311.jpg', 'image_00312.jpg', 'image_00313.jpg', 'image_00314.jpg', 'image_00315.jpg', 'image_00316.jpg', 'image_00317.jpg', 'image_00318.jpg', 'image_00319.jpg', 'image_00320.jpg', 'image_00321.jpg', 'image_00322.jpg', 'image_00323.jpg', 'image_00324.jpg', 'image_00325.jpg', 'image_00326.jpg', 'image_00327.jpg', 'image_00328.jpg', 'image_00329.jpg', 'image_00330.jpg', 'image_00331.jpg', 'image_00332.jpg', 'image_00333.jpg', 'image_00334.jpg', 'image_00335.jpg', 'image_00336.jpg', 'image_00337.jpg', 'image_00338.jpg', 'image_00339.jpg', 'image_00340.jpg', 'image_00341.jpg', 'image_00342.jpg', 'image_00343.jpg', 'image_00344.jpg', 'image_00345.jpg', 'image_00346.jpg', 'image_00347.jpg', 'image_00348.jpg', 'image_00349.jpg', 'image_00350.jpg', 'image_00351.jpg', 'image_00352.jpg', 'image_00353.jpg', 'image_00354.jpg', 'image_00355.jpg', 'image_00356.jpg', 'image_00357.jpg', 'image_00358.jpg', 'image_00359.jpg', 'image_00360.jpg', 'image_00361.jpg', 'image_00362.jpg', 'image_00363.jpg', 'image_00364.jpg', 'image_00365.jpg', 'image_00366.jpg', 'image_00367.jpg', 'image_00368.jpg', 'image_00369.jpg', 'image_00370.jpg', 'image_00371.jpg', 'image_00372.jpg', 'image_00373.jpg', 'image_00374.jpg', 'image_00375.jpg', 'image_00376.jpg', 'image_00377.jpg', 'image_00378.jpg', 'image_00379.jpg', 'image_00380.jpg', 'image_00381.jpg', 'image_00382.jpg', 'image_00383.jpg', 'image_00384.jpg', 'image_00385.jpg', 'image_00386.jpg', 'image_00387.jpg', 'image_00388.jpg', 'image_00389.jpg', 'image_00390.jpg', 'image_00391.jpg', 'image_00392.jpg', 'image_00393.jpg', 'image_00394.jpg', 'image_00395.jpg', 'image_00396.jpg', 'image_00397.jpg', 'image_00398.jpg', 'image_00399.jpg', 'image_00400.jpg']
8189
8189
Loading model parameters...
Compiling encoders...
Loading tables...
Traceback (most recent call last):
  File "/home/amax/ypy/text-to-image-master/Codes3/data_loader.py", line 113, in <module>
    main()
  File "/home/amax/ypy/text-to-image-master/Codes3/data_loader.py", line 108, in main
    save_caption_vectors_flowers(args.data_dir)
  File "/home/amax/ypy/text-to-image-master/Codes3/data_loader.py", line 77, in save_caption_vectors_flowers
    model = skipthoughts.load_model()
  File "/home/amax/ypy/text-to-image-master/Codes3/skipthoughts.py", line 61, in load_model
    utable, btable = load_tables()
  File "/home/amax/ypy/text-to-image-master/Codes3/skipthoughts.py", line 82, in load_tables
    btable = numpy.load(path_to_tables + 'btable.npy',encoding='latin1')
  File "/home/amax/anaconda3/lib/python3.5/site-packages/numpy/lib/npyio.py", line 421, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/amax/anaconda3/lib/python3.5/site-packages/numpy/lib/format.py", line 650, in read_array
    array = pickle.load(fp, **pickle_kwargs)
EOFError: Ran out of input

**Comment by LBJYPY** [comment]
@paarthneekhara  could you please help me  to solve this error

**Comment by ldd071** [comment]
how can solve it??please reply as soon as possible
