### ISSUE TITLE
Data Loader

### ISSUE THREAD

**Issue by shiningstar93** [paarthneekhara/text-to-image#65]
['image_06288.jpg', 'image_08158.jpg', 'image_05755.jpg', 'image_02589.jpg', 'image_07136.jpg', 'image_00386.jpg', 'image_03853.jpg', 'image_02558.jpg', 'image_02394.jpg', 'image_03728.jpg', 'image_00459.jpg', 'image_02971.jpg', 'image_05165.jpg', 'image_00200.jpg', 'image_05604.jpg', 'image_00165.jpg', 'image_06698.jpg', 'image_07523.jpg', 'image_05897.jpg', 'image_00893.jpg', 'image_07566.jpg', 'image_02521.jpg', 'image_02177.jpg', 'image_08017.jpg', 'image_04124.jpg', 'image_01274.jpg', 'image_01322.jpg', 'image_05418.jpg', 'image_03020.jpg', 'image_04845.jpg', 'image_02937.jpg', 'image_04535.jpg', 'image_05900.jpg', 'image_06085.jpg', 'image_01547.jpg', 'image_01584.jpg', 'image_03256.jpg', 'image_04241.jpg', 'image_07573.jpg', 'image_07429.jpg', 'image_05473.jpg', 'image_03866.jpg', 'image_02641.jpg', 'image_02421.jpg', 'image_03829.jpg', 'image_00172.jpg', 'image_04244.jpg', 'image_01564.jpg', 'image_00103.jpg', 'image_00394.jpg', 'image_06692.jpg', 'image_07503.jpg', 'image_02566.jpg', 'image_07964.jpg', 'image_07431.jpg', 'image_04724.jpg', 'image_02230.jpg', 'image_02434.jpg', 'image_05386.jpg', 'image_05502.jpg', 'image_00485.jpg', 'image_04411.jpg', 'image_01350.jpg', 'image_03127.jpg', 'image_06379.jpg', 'image_05504.jpg', 'image_04690.jpg', 'image_06777.jpg', 'image_04227.jpg', 'image_02020.jpg', 'image_03077.jpg', 'image_07699.jpg', 'image_05176.jpg', 'image_03054.jpg', 'image_03833.jpg', 'image_04077.jpg', 'image_04581.jpg', 'image_01178.jpg', 'image_05925.jpg', 'image_04951.jpg', 'image_01707.jpg', 'image_00215.jpg', 'image_00497.jpg', 'image_01570.jpg', 'image_04317.jpg', 'image_04728.jpg', 'image_00960.jpg', 'image_00775.jpg', 'image_05898.jpg', 'image_00606.jpg', 'image_01223.jpg', 'image_03507.jpg', 'image_00898.jpg', 'image_07854.jpg', 'image_05882.jpg', 'image_06700.jpg', 'image_04863.jpg', 'image_01872.jpg', 'image_06113.jpg', 'image_05639.jpg']
8189
8189
Loading model parameters...
Compiling encoders...
Loading tables...
Traceback (most recent call last):
  File "data_loader.py", line 110, in <module>
    main()
  File "data_loader.py", line 105, in main
    save_caption_vectors_flowers(args.data_dir)
  File "data_loader.py", line 76, in save_caption_vectors_flowers
    model = skipthoughts.load_model()
  File "/home/sarah/text-to-image/skipthoughts.py", line 60, in load_model
    utable, btable = load_tables()
  File "/home/sarah/text-to-image/skipthoughts.py", line 80, in load_tables
    utable = numpy.load(path_to_tables + 'utable.npy',encoding='latin1')
  File "/home/sarah/.local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/sarah/.local/lib/python3.7/site-packages/numpy/lib/format.py", line 739, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

How can I solve it?
Python 3.7
Numpy 1.18.4
Tensorflow 2.2.1
Gast 0.3.3

**Comment by shiningstar93** [comment]
I fixed this error by changing python version.
