### ISSUE TITLE
generating images error

### ISSUE THREAD

**Issue by anudeekshith** [paarthneekhara/text-to-image#66]
Traceback (most recent call last):
  File "encode_text.py", line 32, in <module>
    main()
  File "encode_text.py", line 16, in main
    model = skipthoughts.load_model()
  File "/home/anu/Downloads/TAC-GAN-master/skipthoughts.py", line 60, in load_model
    utable, btable = load_tables()
  File "/home/anu/Downloads/TAC-GAN-master/skipthoughts.py", line 80, in load_tables
    utable = numpy.load(path_to_tables + 'utable.npy', encoding='bytes')
  File "/home/anu/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/anu/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 739, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
 how to solve this this

**Comment by halng** [comment]
Change utable = numpy.load(path_to_tables + 'utable.npy', encoding='bytes')
to utable = numpy.load(path_to_tables + 'utable.npy', encoding='bytes', allow_pickle=True)
